# Generated by Django 5.1.6 on 2025-02-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seat_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
    ]
